/**
 * Vercel cron — pulls one pending portfolio_build_jobs row, generates the
 * page TSX via cascade LLM, pushes it to the target repo via GitHub
 * Contents API, marks the job done.
 *
 * Schedule: */10 * * * * (declared in vercel.json)
 * Auth: x-vercel-cron OR x-cron-secret matches CRON_SECRET.
 *
 * Heartbeat: writes start/end into public.cron_runs (cron_name='portfolio-build').
 */
import { NextResponse } from 'next/server'
import { createSupabaseAdmin } from '@/lib/supabase-server'
import { generatePage } from '@/lib/portfolio/generator'
import { pushFile } from '@/lib/portfolio/github-push'
import type { PageType } from '@/lib/portfolio/products'

export const runtime = 'nodejs'
export const maxDuration = 300
export const dynamic = 'force-dynamic'

const CRON_NAME = 'portfolio-build'
const HOST = 'vercel'

type Job = {
  id: number
  product_slug: string
  page_type: PageType
  brief: Record<string, unknown> | null
  attempts: number
}

async function authorise(req: Request): Promise<boolean> {
  if (req.headers.get('x-vercel-cron')) return true
  const token =
    req.headers.get('x-cron-secret') ??
    req.headers.get('authorization')?.replace(/^Bearer\s+/i, '')
  return !!process.env.CRON_SECRET && token === process.env.CRON_SECRET
}

async function heartbeatStart(admin: ReturnType<typeof createSupabaseAdmin>): Promise<number | null> {
  const { data, error } = await admin
    .from('cron_runs')
    .insert({ cron_name: CRON_NAME, host: HOST })
    .select('id')
    .single()
  if (error) return null
  return data?.id ?? null
}

async function heartbeatFinish(
  admin: ReturnType<typeof createSupabaseAdmin>,
  id: number | null,
  success: boolean,
  errorMsg: string | null,
  items: number,
) {
  if (!id) return
  await admin
    .from('cron_runs')
    .update({
      finished_at: new Date().toISOString(),
      success,
      error_msg: errorMsg,
      items_processed: items,
    })
    .eq('id', id)
}

async function claimJob(admin: ReturnType<typeof createSupabaseAdmin>): Promise<Job | null> {
  // Atomic claim: select + update where status = 'pending'.
  // Use a single UPDATE ... RETURNING via RPC if defined, else simple UPDATE.
  const { data, error } = await admin
    .from('portfolio_build_jobs')
    .update({ status: 'processing', claimed_at: new Date().toISOString() })
    .eq('status', 'pending')
    .order('id', { ascending: true })
    .limit(1)
    .select('id, product_slug, page_type, brief, attempts')
    .maybeSingle()
  if (error || !data) return null
  return data as Job
}

async function markDone(
  admin: ReturnType<typeof createSupabaseAdmin>,
  jobId: number,
  generatedPath: string,
  commitSha: string,
  htmlUrl: string,
  provider: string,
  costUsd: number | undefined,
) {
  await admin
    .from('portfolio_build_jobs')
    .update({
      status: 'done',
      finished_at: new Date().toISOString(),
      generated_path: generatedPath,
      commit_sha: commitSha,
      html_url: htmlUrl,
      provider,
      cost_usd: costUsd ?? null,
    })
    .eq('id', jobId)
}

async function markFailed(
  admin: ReturnType<typeof createSupabaseAdmin>,
  jobId: number,
  errorMsg: string,
  attempts: number,
) {
  const newStatus = attempts >= 2 ? 'failed' : 'pending' // re-queue twice
  await admin
    .from('portfolio_build_jobs')
    .update({
      status: newStatus,
      attempts: attempts + 1,
      last_error: errorMsg.slice(0, 1000),
      claimed_at: null,
    })
    .eq('id', jobId)
}

async function processJob(
  admin: ReturnType<typeof createSupabaseAdmin>,
  job: Job,
): Promise<{ ok: boolean; message: string }> {
  const briefText =
    typeof job.brief === 'object' && job.brief && 'text' in job.brief
      ? String((job.brief as { text: unknown }).text ?? '')
      : ''

  const result = await generatePage({
    productSlug: job.product_slug,
    pageType: job.page_type,
    brief: briefText,
  })

  const push = await pushFile({
    owner: result.product.repoOwner,
    repo: result.product.repoName,
    branch: result.product.repoBranch,
    path: result.path,
    content: result.tsx,
    message: `feat(${result.product.slug}/${result.pageType}): generated by portfolio-builder #${job.id}`,
  })

  await markDone(admin, job.id, result.path, push.commitSha, push.htmlUrl, result.provider, result.costUsd)
  return { ok: true, message: `${result.product.slug}/${result.pageType} → ${push.htmlUrl}` }
}

async function run(req: Request) {
  if (!(await authorise(req))) {
    return NextResponse.json({ ok: false, error: 'unauthorized' }, { status: 401 })
  }

  const admin = createSupabaseAdmin()
  const hbId = await heartbeatStart(admin)

  let processed = 0
  let lastError: string | null = null
  const messages: string[] = []

  // Process up to 10 jobs per fire (Vercel Hobby = 1 cron/day, so we batch).
  // Use ?max=N query param to override (caps at 30).
  const url = new URL(req.url)
  const maxFromQuery = parseInt(url.searchParams.get('max') ?? '', 10)
  const max = Math.min(Number.isFinite(maxFromQuery) && maxFromQuery > 0 ? maxFromQuery : 10, 30)
  for (let i = 0; i < max; i++) {
    const job = await claimJob(admin)
    if (!job) break
    try {
      const r = await processJob(admin, job)
      processed++
      messages.push(r.message)
    } catch (e) {
      const msg = (e as Error).message ?? 'unknown'
      lastError = msg
      await markFailed(admin, job.id, msg, job.attempts)
      messages.push(`FAIL job#${job.id}: ${msg}`)
    }
  }

  await heartbeatFinish(admin, hbId, !lastError, lastError, processed)

  return NextResponse.json({
    ok: !lastError,
    processed,
    messages,
    error: lastError,
  })
}

export async function GET(req: Request) {
  return run(req)
}
export async function POST(req: Request) {
  return run(req)
}
