/**
 * GET /api/cron/refresh-country-pricing
 *
 * Quarterly refresh of the `country_pricing_multiplier` Supabase table.
 * Re-reads the bundled static JSON (data/country-pricing.json) that is
 * regenerated by `scripts/build-country-pricing.ts` before each deploy,
 * and upserts all rows.
 *
 * Called by Vercel Cron (see vercel.json) every 90 days:
 *   { "path": "/api/cron/refresh-country-pricing", "schedule": "0 4 1 1,4,7,10 *" }
 *
 * Auth: CRON_SECRET header (matches Vercel Cron default).
 */
import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import pricingData from '@/data/country-pricing.json';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type Row = {
  iso2: string;
  iso3: string;
  name: string;
  currency: string;
  multiplier: number;
  components?: unknown;
};
type File = { version: string; computed_at: string; countries: Row[] };

export async function GET(req: Request) {
  const auth = req.headers.get('authorization') ?? '';
  const expected = `Bearer ${process.env.CRON_SECRET ?? ''}`;
  if (!process.env.CRON_SECRET || auth !== expected) {
    return NextResponse.json({ error: 'unauthorized' }, { status: 401 });
  }

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    return NextResponse.json({ error: 'supabase env missing' }, { status: 500 });
  }

  const supabase = createClient(url, key, { auth: { persistSession: false } });
  const file = pricingData as File;

  const rows = file.countries.map((c) => ({
    iso2: c.iso2,
    iso3: c.iso3,
    name: c.name,
    currency: c.currency,
    multiplier: c.multiplier,
    components: c.components ?? null,
    computed_at: file.computed_at,
  }));

  const { error, count } = await supabase
    .from('country_pricing_multiplier')
    .upsert(rows, { onConflict: 'iso2', count: 'exact' });

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({
    ok: true,
    upserted: count ?? rows.length,
    file_version: file.version,
    file_computed_at: file.computed_at,
  });
}
