-- Seed 198 countries for country_pricing_multiplier
-- Regenerated via: npx tsx scripts/build-country-pricing.ts
-- Source: data/country-pricing.seed.sql (idempotent upsert)

insert into country_pricing_multiplier (iso2, iso3, name, currency, multiplier) values
  ('US', 'USA', 'United States', 'USD', 1.00),
  ('CA', 'CAN', 'Canada', 'CAD', 0.80),
  ('MX', 'MEX', 'Mexico', 'MXN', 0.45),
  ('GT', 'GTM', 'Guatemala', 'GTQ', 0.40),
  ('HN', 'HND', 'Honduras', 'HNL', 0.35),
  ('SV', 'SLV', 'El Salvador', 'USD', 0.40),
  ('NI', 'NIC', 'Nicaragua', 'NIO', 0.35),
  ('CR', 'CRI', 'Costa Rica', 'CRC', 0.55),
  ('PA', 'PAN', 'Panama', 'PAB', 0.60),
  ('CU', 'CUB', 'Cuba', 'CUP', 0.30),
  ('DO', 'DOM', 'Dominican Republic', 'DOP', 0.50),
  ('HT', 'HTI', 'Haiti', 'HTG', 0.25),
  ('JM', 'JAM', 'Jamaica', 'JMD', 0.45),
  ('TT', 'TTO', 'Trinidad and Tobago', 'TTD', 0.55),
  ('BS', 'BHS', 'Bahamas', 'BSD', 0.75),
  ('BB', 'BRB', 'Barbados', 'BBD', 0.55),
  ('BZ', 'BLZ', 'Belize', 'BZD', 0.40),
  ('BR', 'BRA', 'Brazil', 'BRL', 0.45),
  ('AR', 'ARG', 'Argentina', 'ARS', 0.50),
  ('CL', 'CHL', 'Chile', 'CLP', 0.55),
  ('CO', 'COL', 'Colombia', 'COP', 0.45),
  ('PE', 'PER', 'Peru', 'PEN', 0.40),
  ('VE', 'VEN', 'Venezuela', 'VES', 0.30),
  ('EC', 'ECU', 'Ecuador', 'USD', 0.40),
  ('BO', 'BOL', 'Bolivia', 'BOB', 0.35),
  ('PY', 'PRY', 'Paraguay', 'PYG', 0.40),
  ('UY', 'URY', 'Uruguay', 'UYU', 0.60),
  ('GY', 'GUY', 'Guyana', 'GYD', 0.80),
  ('SR', 'SUR', 'Suriname', 'SRD', 0.45),
  ('FR', 'FRA', 'France', 'EUR', 0.80),
  ('DE', 'DEU', 'Germany', 'EUR', 0.85),
  ('IT', 'ITA', 'Italy', 'EUR', 0.75),
  ('ES', 'ESP', 'Spain', 'EUR', 0.70),
  ('PT', 'PRT', 'Portugal', 'EUR', 0.65),
  ('NL', 'NLD', 'Netherlands', 'EUR', 0.95),
  ('BE', 'BEL', 'Belgium', 'EUR', 0.90),
  ('LU', 'LUX', 'Luxembourg', 'EUR', 1.20),
  ('AT', 'AUT', 'Austria', 'EUR', 0.90),
  ('CH', 'CHE', 'Switzerland', 'CHF', 1.15),
  ('IE', 'IRL', 'Ireland', 'EUR', 1.15),
  ('GB', 'GBR', 'United Kingdom', 'GBP', 0.80),
  ('MT', 'MLT', 'Malta', 'EUR', 0.80),
  ('GR', 'GRC', 'Greece', 'EUR', 0.65),
  ('PR', 'PRI', 'Puerto Rico', 'USD', 0.70),
  ('GL', 'GRL', 'Greenland', 'DKK', 0.85),
  ('NC', 'NCL', 'New Caledonia', 'XPF', 0.65),
  ('PF', 'PYF', 'French Polynesia', 'XPF', 0.60),
  ('CY', 'CYP', 'Cyprus', 'EUR', 0.75),
  ('MC', 'MCO', 'Monaco', 'EUR', 1.20),
  ('LI', 'LIE', 'Liechtenstein', 'CHF', 1.25),
  ('AD', 'AND', 'Andorra', 'EUR', 0.85),
  ('SM', 'SMR', 'San Marino', 'EUR', 0.85),
  ('VA', 'VAT', 'Vatican City', 'EUR', 0.80),
  ('SE', 'SWE', 'Sweden', 'SEK', 0.85),
  ('NO', 'NOR', 'Norway', 'NOK', 1.05),
  ('DK', 'DNK', 'Denmark', 'DKK', 0.95),
  ('FI', 'FIN', 'Finland', 'EUR', 0.85),
  ('IS', 'ISL', 'Iceland', 'ISK', 1.05),
  ('PL', 'POL', 'Poland', 'PLN', 0.65),
  ('CZ', 'CZE', 'Czechia', 'CZK', 0.70),
  ('SK', 'SVK', 'Slovakia', 'EUR', 0.65),
  ('HU', 'HUN', 'Hungary', 'HUF', 0.65),
  ('RO', 'ROU', 'Romania', 'RON', 0.60),
  ('BG', 'BGR', 'Bulgaria', 'BGN', 0.55),
  ('HR', 'HRV', 'Croatia', 'EUR', 0.60),
  ('SI', 'SVN', 'Slovenia', 'EUR', 0.70),
  ('EE', 'EST', 'Estonia', 'EUR', 0.65),
  ('LV', 'LVA', 'Latvia', 'EUR', 0.65),
  ('LT', 'LTU', 'Lithuania', 'EUR', 0.70),
  ('RS', 'SRB', 'Serbia', 'RSD', 0.45),
  ('BA', 'BIH', 'Bosnia and Herzegovina', 'BAM', 0.45),
  ('MK', 'MKD', 'North Macedonia', 'MKD', 0.40),
  ('ME', 'MNE', 'Montenegro', 'EUR', 0.50),
  ('AL', 'ALB', 'Albania', 'ALL', 0.40),
  ('XK', 'XKX', 'Kosovo', 'EUR', 0.40),
  ('MD', 'MDA', 'Moldova', 'MDL', 0.40),
  ('UA', 'UKR', 'Ukraine', 'UAH', 0.35),
  ('BY', 'BLR', 'Belarus', 'BYN', 0.40),
  ('RU', 'RUS', 'Russia', 'RUB', 0.50),
  ('TR', 'TUR', 'Türkiye', 'TRY', 0.60),
  ('IL', 'ISR', 'Israel', 'ILS', 0.80),
  ('SA', 'SAU', 'Saudi Arabia', 'SAR', 0.80),
  ('AE', 'ARE', 'United Arab Emirates', 'AED', 1.00),
  ('QA', 'QAT', 'Qatar', 'QAR', 1.05),
  ('BH', 'BHR', 'Bahrain', 'BHD', 0.80),
  ('KW', 'KWT', 'Kuwait', 'KWD', 0.75),
  ('OM', 'OMN', 'Oman', 'OMR', 0.65),
  ('JO', 'JOR', 'Jordan', 'JOD', 0.40),
  ('LB', 'LBN', 'Lebanon', 'LBP', 0.40),
  ('IQ', 'IRQ', 'Iraq', 'IQD', 0.35),
  ('IR', 'IRN', 'Iran', 'IRR', 0.35),
  ('SY', 'SYR', 'Syria', 'SYP', 0.20),
  ('YE', 'YEM', 'Yemen', 'YER', 0.20),
  ('PS', 'PSE', 'Palestine', 'ILS', 0.35),
  ('CN', 'CHN', 'China', 'CNY', 0.45),
  ('JP', 'JPN', 'Japan', 'JPY', 0.60),
  ('KR', 'KOR', 'South Korea', 'KRW', 0.75),
  ('KP', 'PRK', 'North Korea', 'KPW', 0.20),
  ('TW', 'TWN', 'Taiwan', 'TWD', 0.75),
  ('HK', 'HKG', 'Hong Kong', 'HKD', 0.85),
  ('MO', 'MAC', 'Macao', 'MOP', 0.90),
  ('SG', 'SGP', 'Singapore', 'SGD', 1.15),
  ('MY', 'MYS', 'Malaysia', 'MYR', 0.45),
  ('TH', 'THA', 'Thailand', 'THB', 0.45),
  ('VN', 'VNM', 'Vietnam', 'VND', 0.35),
  ('ID', 'IDN', 'Indonesia', 'IDR', 0.30),
  ('PH', 'PHL', 'Philippines', 'PHP', 0.30),
  ('IN', 'IND', 'India', 'INR', 0.25),
  ('PK', 'PAK', 'Pakistan', 'PKR', 0.20),
  ('BD', 'BGD', 'Bangladesh', 'BDT', 0.25),
  ('LK', 'LKA', 'Sri Lanka', 'LKR', 0.30),
  ('NP', 'NPL', 'Nepal', 'NPR', 0.25),
  ('BT', 'BTN', 'Bhutan', 'BTN', 0.30),
  ('MV', 'MDV', 'Maldives', 'MVR', 0.50),
  ('MM', 'MMR', 'Myanmar', 'MMK', 0.20),
  ('KH', 'KHM', 'Cambodia', 'KHR', 0.25),
  ('LA', 'LAO', 'Laos', 'LAK', 0.25),
  ('MN', 'MNG', 'Mongolia', 'MNT', 0.35),
  ('KZ', 'KAZ', 'Kazakhstan', 'KZT', 0.45),
  ('UZ', 'UZB', 'Uzbekistan', 'UZS', 0.30),
  ('KG', 'KGZ', 'Kyrgyzstan', 'KGS', 0.25),
  ('TJ', 'TJK', 'Tajikistan', 'TJS', 0.25),
  ('TM', 'TKM', 'Turkmenistan', 'TMT', 0.35),
  ('AF', 'AFG', 'Afghanistan', 'AFN', 0.20),
  ('AM', 'ARM', 'Armenia', 'AMD', 0.40),
  ('AZ', 'AZE', 'Azerbaijan', 'AZN', 0.40),
  ('GE', 'GEO', 'Georgia', 'GEL', 0.45),
  ('TL', 'TLS', 'Timor-Leste', 'USD', 0.25),
  ('BN', 'BRN', 'Brunei', 'BND', 0.80),
  ('AU', 'AUS', 'Australia', 'AUD', 0.85),
  ('NZ', 'NZL', 'New Zealand', 'NZD', 0.75),
  ('PG', 'PNG', 'Papua New Guinea', 'PGK', 0.30),
  ('FJ', 'FJI', 'Fiji', 'FJD', 0.40),
  ('SB', 'SLB', 'Solomon Islands', 'SBD', 0.30),
  ('VU', 'VUT', 'Vanuatu', 'VUV', 0.30),
  ('WS', 'WSM', 'Samoa', 'WST', 0.30),
  ('TO', 'TON', 'Tonga', 'TOP', 0.30),
  ('KI', 'KIR', 'Kiribati', 'AUD', 0.30),
  ('MH', 'MHL', 'Marshall Islands', 'USD', 0.35),
  ('FM', 'FSM', 'Micronesia', 'USD', 0.30),
  ('PW', 'PLW', 'Palau', 'USD', 0.40),
  ('NR', 'NRU', 'Nauru', 'AUD', 0.35),
  ('TV', 'TUV', 'Tuvalu', 'AUD', 0.30),
  ('CK', 'COK', 'Cook Islands', 'NZD', 0.45),
  ('EG', 'EGY', 'Egypt', 'EGP', 0.30),
  ('MA', 'MAR', 'Morocco', 'MAD', 0.30),
  ('DZ', 'DZA', 'Algeria', 'DZD', 0.30),
  ('TN', 'TUN', 'Tunisia', 'TND', 0.30),
  ('LY', 'LBY', 'Libya', 'LYD', 0.35),
  ('SD', 'SDN', 'Sudan', 'SDG', 0.20),
  ('SS', 'SSD', 'South Sudan', 'SSP', 0.20),
  ('ET', 'ETH', 'Ethiopia', 'ETB', 0.20),
  ('KE', 'KEN', 'Kenya', 'KES', 0.30),
  ('TZ', 'TZA', 'Tanzania', 'TZS', 0.20),
  ('UG', 'UGA', 'Uganda', 'UGX', 0.20),
  ('RW', 'RWA', 'Rwanda', 'RWF', 0.20),
  ('BI', 'BDI', 'Burundi', 'BIF', 0.20),
  ('SO', 'SOM', 'Somalia', 'SOS', 0.20),
  ('DJ', 'DJI', 'Djibouti', 'DJF', 0.25),
  ('ER', 'ERI', 'Eritrea', 'ERN', 0.20),
  ('NG', 'NGA', 'Nigeria', 'NGN', 0.20),
  ('GH', 'GHA', 'Ghana', 'GHS', 0.20),
  ('CI', 'CIV', 'Côte d''Ivoire', 'XOF', 0.25),
  ('SN', 'SEN', 'Senegal', 'XOF', 0.25),
  ('ML', 'MLI', 'Mali', 'XOF', 0.20),
  ('BF', 'BFA', 'Burkina Faso', 'XOF', 0.20),
  ('NE', 'NER', 'Niger', 'XOF', 0.20),
  ('TD', 'TCD', 'Chad', 'XAF', 0.20),
  ('BJ', 'BEN', 'Benin', 'XOF', 0.20),
  ('TG', 'TGO', 'Togo', 'XOF', 0.20),
  ('GN', 'GIN', 'Guinea', 'GNF', 0.20),
  ('GW', 'GNB', 'Guinea-Bissau', 'XOF', 0.20),
  ('SL', 'SLE', 'Sierra Leone', 'SLL', 0.20),
  ('LR', 'LBR', 'Liberia', 'LRD', 0.20),
  ('GM', 'GMB', 'Gambia', 'GMD', 0.20),
  ('CV', 'CPV', 'Cabo Verde', 'CVE', 0.30),
  ('MR', 'MRT', 'Mauritania', 'MRU', 0.25),
  ('CM', 'CMR', 'Cameroon', 'XAF', 0.25),
  ('CF', 'CAF', 'Central African Republic', 'XAF', 0.20),
  ('GA', 'GAB', 'Gabon', 'XAF', 0.35),
  ('CG', 'COG', 'Congo', 'XAF', 0.25),
  ('CD', 'COD', 'DR Congo', 'CDF', 0.20),
  ('AO', 'AGO', 'Angola', 'AOA', 0.25),
  ('ZM', 'ZMB', 'Zambia', 'ZMW', 0.20),
  ('ZW', 'ZWE', 'Zimbabwe', 'ZWL', 0.20),
  ('MW', 'MWI', 'Malawi', 'MWK', 0.20),
  ('MZ', 'MOZ', 'Mozambique', 'MZN', 0.20),
  ('BW', 'BWA', 'Botswana', 'BWP', 0.40),
  ('NA', 'NAM', 'Namibia', 'NAD', 0.35),
  ('LS', 'LSO', 'Lesotho', 'LSL', 0.25),
  ('SZ', 'SWZ', 'Eswatini', 'SZL', 0.30),
  ('ZA', 'ZAF', 'South Africa', 'ZAR', 0.35),
  ('MG', 'MDG', 'Madagascar', 'MGA', 0.20),
  ('MU', 'MUS', 'Mauritius', 'MUR', 0.50),
  ('SC', 'SYC', 'Seychelles', 'SCR', 0.55),
  ('KM', 'COM', 'Comoros', 'KMF', 0.20),
  ('ST', 'STP', 'São Tomé and Príncipe', 'STN', 0.25),
  ('GQ', 'GNQ', 'Equatorial Guinea', 'XAF', 0.40)
on conflict (iso2) do update set
  iso3 = excluded.iso3,
  name = excluded.name,
  currency = excluded.currency,
  multiplier = excluded.multiplier,
  updated_at = now();
